package latex

import (
	"fmt"
	"strings"
	"unicode"
)

// PaperCitation mirrors modules.PaperCitation for use in the latex package.
type PaperCitation struct {
	Key     string
	Authors string
	Title   string
	Year    string
	Journal string
	DOI     string
}

// GenerateBibFile produces a complete .bib file from the given citations.
// Each citation becomes an @article entry with the citation key in authorYear format.
// Fields: author, title, journal, year, doi.
func GenerateBibFile(citations []PaperCitation) string {
	if len(citations) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("%% Bibliography generated by SLR Pipeline\n")
	b.WriteString("%% Format: BibTeX (natbib/apalike compatible)\n\n")

	for _, c := range citations {
		b.WriteString(fmt.Sprintf("@article{%s,\n", c.Key))
		b.WriteString(fmt.Sprintf("  author  = {%s},\n", bibEscapeValue(c.Authors)))
		b.WriteString(fmt.Sprintf("  title   = {%s},\n", bibEscapeValue(c.Title)))
		if c.Journal != "" {
			b.WriteString(fmt.Sprintf("  journal = {%s},\n", bibEscapeValue(c.Journal)))
		}
		b.WriteString(fmt.Sprintf("  year    = {%s},\n", c.Year))
		if c.DOI != "" {
			doi := strings.TrimPrefix(c.DOI, "https://doi.org/")
			doi = strings.TrimPrefix(doi, "http://doi.org/")
			b.WriteString(fmt.Sprintf("  doi     = {%s},\n", doi))
		}
		b.WriteString("}\n\n")
	}

	return strings.TrimSpace(b.String())
}

// bibEscapeValue escapes special BibTeX characters in field values.
// Only escapes characters that would break BibTeX parsing; preserves
// accented/unicode characters as-is (modern BibTeX handles UTF-8).
func bibEscapeValue(s string) string {
	// BibTeX field values inside braces only need minimal escaping:
	// & and % are the main problematic chars. # is a concat operator outside braces.
	r := strings.NewReplacer(
		"&", `\&`,
		"%", `\%`,
		"#", `\#`,
	)
	return r.Replace(s)
}

// BuildAcademicLatex generates a complete article-class LaTeX document suitable for
// Overleaf/natbib compilation. The sections parameter contains section-name to
// LaTeX-content mappings. Content is already in LaTeX format (with \cite{} commands)
// and is NOT escaped.
//
// Parameters:
//   - title: manuscript title
//   - author: author string (empty string is acceptable)
//   - abstract: abstract text (already in LaTeX)
//   - keywords: semicolon-separated keywords
//   - sections: ordered section content (Introduction, Methods, Results, Discussion, etc.)
//   - bibFile: bibliography file name without extension (e.g., "references")
//   - prismaFigure: complete TikZ PRISMA flow figure (empty string to omit). When
//     present it is placed as Figure 1 (after keywords, before Introduction) and the
//     required tikz packages are added to the preamble.
func BuildAcademicLatex(title, author, abstract, keywords string, sections map[string]string, bibFile, prismaFigure string) string {
	var out strings.Builder

	// Document class and packages
	out.WriteString("\\documentclass[12pt]{article}\n")
	out.WriteString("\\usepackage[utf8]{inputenc}\n")
	out.WriteString("\\usepackage[T1]{fontenc}\n")
	out.WriteString("\\usepackage{times}\n")
	out.WriteString("\\usepackage[margin=1in]{geometry}\n")
	out.WriteString("\\usepackage{setspace}\n")
	out.WriteString("\\usepackage{graphicx}\n")
	out.WriteString("\\usepackage{hyperref}\n")
	out.WriteString("\\usepackage{longtable}\n")
	out.WriteString("\\usepackage{natbib}\n")
	if strings.TrimSpace(prismaFigure) != "" {
		out.WriteString("\\usepackage{tikz}\n")
		out.WriteString("\\usetikzlibrary{positioning,arrows.meta}\n")
	}
	out.WriteString("\n")
	out.WriteString("\\doublespacing\n")
	out.WriteString("\n")

	// Title and author
	if title != "" {
		out.WriteString("\\title{" + escapeLatexTitle(title) + "}\n")
	}
	if author != "" {
		out.WriteString("\\author{" + escapeLatexTitle(author) + "}\n")
	}
	out.WriteString("\\date{}\n")
	out.WriteString("\n")
	out.WriteString("\\begin{document}\n")
	out.WriteString("\n")

	if title != "" {
		out.WriteString("\\maketitle\n")
		out.WriteString("\n")
	}

	// Abstract
	if abstract != "" {
		out.WriteString("\\begin{abstract}\n")
		out.WriteString(abstract + "\n")
		out.WriteString("\\end{abstract}\n")
		out.WriteString("\n")
	}

	// Keywords
	if keywords != "" {
		out.WriteString("\\noindent\\textbf{Keywords:} " + escapeLatexTitle(keywords) + "\n")
		out.WriteString("\n")
	}

	// PRISMA flow diagram (Figure 1) -- placed before Introduction so its float number
	// is 1, matching the "Figure 1" references in Methods/Results.
	if strings.TrimSpace(prismaFigure) != "" {
		out.WriteString(prismaFigure + "\n\n")
	}

	// Sections in standard academic order
	sectionOrder := []struct {
		key   string
		label string
	}{
		{"Introduction", "Introduction"},
		{"Methods", "Methods"},
		{"Results", "Results"},
		{"Discussion", "Discussion"},
		{"Future Research", "Future Research"},
		{"Conclusions", "Conclusions"},
	}

	for _, sec := range sectionOrder {
		content, ok := sections[sec.key]
		if !ok || strings.TrimSpace(content) == "" {
			continue
		}
		// The content is already in LaTeX format and may already contain \section{} commands.
		// If it starts with a \section or \subsection, use it as-is.
		// Otherwise, wrap it with a \section{} header.
		trimmed := strings.TrimSpace(content)
		if strings.HasPrefix(trimmed, "\\section") || strings.HasPrefix(trimmed, "\\subsection") {
			out.WriteString(content + "\n\n")
		} else {
			out.WriteString("\\section{" + sec.label + "}\n")
			out.WriteString(content + "\n\n")
		}
	}

	// Bibliography
	out.WriteString("\\bibliographystyle{apalike}\n")
	out.WriteString("\\bibliography{" + bibFile + "}\n")
	out.WriteString("\n")
	out.WriteString("\\end{document}\n")

	return out.String()
}

// escapeLatexTitle escapes special LaTeX characters in title/author/keywords text,
// but preserves LaTeX commands that might be present (like accented characters).
// This is a minimal escape for metadata fields only.
func escapeLatexTitle(s string) string {
	// Only escape characters that are problematic in LaTeX text mode
	// but NOT backslash (to preserve any LaTeX commands in the title)
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '&':
			b.WriteString("\\&")
		case '%':
			b.WriteString("\\%")
		case '$':
			b.WriteString("\\$")
		case '#':
			b.WriteString("\\#")
		case '_':
			b.WriteString("\\_")
		case '~':
			b.WriteString("\\textasciitilde{}")
		case '^':
			b.WriteString("\\textasciicircum{}")
		default:
			if unicode.IsPrint(r) || r == '\n' || r == '\t' {
				b.WriteRune(r)
			}
		}
	}
	return b.String()
}
